spring.application.name=typing-speed-test-api


# =========================================================
# SERVER
# =========================================================

server.port=8080


# =========================================================
# TIDB CLOUD DATABASE
# =========================================================

spring.datasource.url=${TIDB_JDBC_URL}
spring.datasource.username=${TIDB_USERNAME}
spring.datasource.password=${TIDB_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =========================================================
# JPA / HIBERNATE
# =========================================================

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.open-in-view=false

spring.jpa.properties.hibernate.format_sql=true


# =========================================================
# JWT
# =========================================================

jwt.secret=${JWT_SECRET}

jwt.expiration=${JWT_EXPIRATION:86400000}


# =========================================================
# LOGGING
# =========================================================

logging.level.root=INFO

logging.level.com.typingspeedtest.api=INFO